-- =====================================================================
-- Cinnamon Hotels & Resorts – Data Warehouse
-- 01_create_schema.sql : Star schema (fact + 5 dimensions)
-- Oracle 21c XE  |  Connect via XEPDB1
-- =====================================================================

-- ---------- DIMENSION: DATE ----------
CREATE TABLE DIM_DATE (
    DATEKEY       NUMBER(8)   PRIMARY KEY,   -- YYYYMMDD
    FULLDATE      DATE,
    DAYOFMONTH    NUMBER(2),
    MONTHNAME     VARCHAR2(15),
    MONTHNUMBER   NUMBER(2),
    QUARTER       VARCHAR2(2),
    YEAR          NUMBER(4),
    SEASON        VARCHAR2(20),
    ISWEEKEND     CHAR(1)
);

-- ---------- DIMENSION: HOTEL ----------
CREATE TABLE DIM_HOTEL (
    HOTELKEY      NUMBER       PRIMARY KEY,
    HOTELNAME     VARCHAR2(100),
    PROPERTYTYPE  VARCHAR2(30),
    CITY          VARCHAR2(50),
    DISTRICT      VARCHAR2(50),
    STARRATING    NUMBER(1),
    NUMROOMS      NUMBER(5)
);

-- ---------- DIMENSION: ROOM TYPE ----------
CREATE TABLE DIM_ROOMTYPE (
    ROOMTYPEKEY   NUMBER       PRIMARY KEY,
    ROOMTYPE      VARCHAR2(30),
    BEDTYPE       VARCHAR2(20),
    MAXOCCUPANCY  NUMBER(2)
);

-- ---------- DIMENSION: CHANNEL ----------
CREATE TABLE DIM_CHANNEL (
    CHANNELKEY    NUMBER       PRIMARY KEY,
    CHANNELNAME   VARCHAR2(50),
    CHANNELTYPE   VARCHAR2(20)
);

-- ---------- DIMENSION: CUSTOMER (profile grain) ----------
CREATE TABLE DIM_CUSTOMER (
    CUSTOMERKEY     NUMBER     PRIMARY KEY,
    CUSTOMERID      VARCHAR2(30),
    SEGMENT         VARCHAR2(20),
    COUNTRY         VARCHAR2(50),
    REPEATGUESTFLAG CHAR(1)
);

-- ---------- FACT: BOOKINGS ----------
CREATE TABLE FACT_BOOKINGS (
    BOOKINGKEY      NUMBER        PRIMARY KEY,
    DATEKEY         NUMBER(8),
    CUSTOMERKEY     NUMBER,
    HOTELKEY        NUMBER,
    ROOMTYPEKEY     NUMBER,
    CHANNELKEY      NUMBER,
    LEADTIMEDAYS    NUMBER(5),
    LENGTHOFSTAY    NUMBER(3),
    ADR             NUMBER(10,2),
    TOTALREVENUE    NUMBER(12,2),
    ISCANCELLED     CHAR(1),
    NUMADULTS       NUMBER(2),
    NUMCHILDREN     NUMBER(2),
    SPECIALREQUESTS NUMBER(2),
    CONSTRAINT FK_FACT_DATE     FOREIGN KEY (DATEKEY)     REFERENCES DIM_DATE(DATEKEY),
    CONSTRAINT FK_FACT_CUST     FOREIGN KEY (CUSTOMERKEY) REFERENCES DIM_CUSTOMER(CUSTOMERKEY),
    CONSTRAINT FK_FACT_HOTEL    FOREIGN KEY (HOTELKEY)    REFERENCES DIM_HOTEL(HOTELKEY),
    CONSTRAINT FK_FACT_ROOMTYPE FOREIGN KEY (ROOMTYPEKEY) REFERENCES DIM_ROOMTYPE(ROOMTYPEKEY),
    CONSTRAINT FK_FACT_CHANNEL  FOREIGN KEY (CHANNELKEY)  REFERENCES DIM_CHANNEL(CHANNELKEY)
);

-- ---------- Indexes on fact foreign keys (speed up joins) ----------
CREATE INDEX IDX_FACT_DATE     ON FACT_BOOKINGS(DATEKEY);
CREATE INDEX IDX_FACT_CUST     ON FACT_BOOKINGS(CUSTOMERKEY);
CREATE INDEX IDX_FACT_HOTEL    ON FACT_BOOKINGS(HOTELKEY);
CREATE INDEX IDX_FACT_ROOMTYPE ON FACT_BOOKINGS(ROOMTYPEKEY);
CREATE INDEX IDX_FACT_CHANNEL  ON FACT_BOOKINGS(CHANNELKEY);
