-- =====================================================================
-- 04_transform_load.sql : Staging -> Star schema
-- Run AFTER NiFi has loaded the three STG_* tables.
-- =====================================================================

-- ---------- Build DIM_CUSTOMER at profile grain ----------
-- Source is anonymised (no customer IDs), so each row = a distinct
-- guest profile: country + customer type + repeat-guest status.
DELETE FROM DIM_CUSTOMER;
COMMIT;

INSERT INTO DIM_CUSTOMER (CUSTOMERKEY, CUSTOMERID, SEGMENT, COUNTRY, REPEATGUESTFLAG)
SELECT rn, 'C' || rn, SEGMENT, COUNTRY, RPT
FROM (
  SELECT ROW_NUMBER() OVER (ORDER BY COUNTRY, SEGMENT, RPT) AS rn, COUNTRY, SEGMENT, RPT
  FROM (
    SELECT DISTINCT
      NVL(TRIM(COUNTRY),'UNK')             AS COUNTRY,
      NVL(TRIM(CUSTOMER_TYPE),'Unknown')   AS SEGMENT,
      CASE WHEN TRIM(IS_REPEATED_GUEST)='1' THEN 'Y' ELSE 'N' END AS RPT
    FROM STG_BOOKINGS_CSV
  )
);
COMMIT;

-- ---------- Load FACT_BOOKINGS ----------
-- Safe numeric conversion (DEFAULT ... ON CONVERSION ERROR) so a single
-- bad value cannot abort the load. Rows with unparseable dates are
-- filtered out naturally by the DIM_DATE join.
DELETE FROM FACT_BOOKINGS;
COMMIT;

INSERT INTO FACT_BOOKINGS
 (BOOKINGKEY, DATEKEY, CUSTOMERKEY, HOTELKEY, ROOMTYPEKEY, CHANNELKEY,
  LEADTIMEDAYS, LENGTHOFSTAY, ADR, TOTALREVENUE, ISCANCELLED,
  NUMADULTS, NUMCHILDREN, SPECIALREQUESTS)
SELECT
  ROWNUM,
  d.DATEKEY, cu.CUSTOMERKEY, h.HOTELKEY, rt.ROOMTYPEKEY, ch.CHANNELKEY,
  s.LEAD_N, s.LOS, s.ADR_N, s.TOTREV, s.CANCEL_FLAG,
  s.ADULTS_N, s.CHILDREN_N, s.SPEC_N
FROM (
  SELECT
    TO_NUMBER(LEAD_TIME DEFAULT 0 ON CONVERSION ERROR) AS LEAD_N,
    (TO_NUMBER(STAYS_IN_WEEKEND_NIGHTS DEFAULT 0 ON CONVERSION ERROR)
     + TO_NUMBER(STAYS_IN_WEEK_NIGHTS DEFAULT 0 ON CONVERSION ERROR)) AS LOS,
    TO_NUMBER(ADR DEFAULT 0 ON CONVERSION ERROR) AS ADR_N,
    ROUND(TO_NUMBER(ADR DEFAULT 0 ON CONVERSION ERROR) *
          (TO_NUMBER(STAYS_IN_WEEKEND_NIGHTS DEFAULT 0 ON CONVERSION ERROR)
           + TO_NUMBER(STAYS_IN_WEEK_NIGHTS DEFAULT 0 ON CONVERSION ERROR)),2) AS TOTREV,
    CASE WHEN TRIM(IS_CANCELED)='1' THEN 'Y' ELSE 'N' END AS CANCEL_FLAG,
    TO_NUMBER(ADULTS DEFAULT 0 ON CONVERSION ERROR) AS ADULTS_N,
    TO_NUMBER(NVL(CHILDREN,'0') DEFAULT 0 ON CONVERSION ERROR) AS CHILDREN_N,
    TO_NUMBER(NVL(TOTAL_OF_SPECIAL_REQUESTS,'0') DEFAULT 0 ON CONVERSION ERROR) AS SPEC_N,
    TO_NUMBER(
      ARRIVAL_DATE_YEAR ||
      LPAD(TO_CHAR(TO_DATE(ARRIVAL_DATE_MONTH,'Month','NLS_DATE_LANGUAGE=ENGLISH'),'MM'),2,'0') ||
      LPAD(ARRIVAL_DATE_DAY_OF_MONTH,2,'0')
      DEFAULT NULL ON CONVERSION ERROR) AS DK,
    NVL(TRIM(COUNTRY),'UNK')             AS COUNTRY_C,
    NVL(TRIM(CUSTOMER_TYPE),'Unknown')   AS SEGMENT_C,
    CASE WHEN TRIM(IS_REPEATED_GUEST)='1' THEN 'Y' ELSE 'N' END AS RPT_C,
    TRIM(HOTEL)                AS HOTEL_C,
    TRIM(RESERVED_ROOM_TYPE)   AS ROOM_C,
    TRIM(DISTRIBUTION_CHANNEL) AS CHAN_C
  FROM STG_BOOKINGS_CSV
) s
JOIN DIM_DATE d      ON d.DATEKEY = s.DK
JOIN DIM_HOTEL h     ON h.HOTELKEY = CASE WHEN s.HOTEL_C='City Hotel' THEN 1 ELSE 3 END
JOIN DIM_ROOMTYPE rt ON rt.ROOMTYPEKEY = CASE s.ROOM_C
        WHEN 'A' THEN 1 WHEN 'B' THEN 1 WHEN 'C' THEN 2 WHEN 'D' THEN 2
        WHEN 'E' THEN 3 WHEN 'F' THEN 4 WHEN 'G' THEN 4 ELSE 5 END
JOIN DIM_CHANNEL ch  ON ch.CHANNELKEY = CASE
        WHEN s.CHAN_C='Direct'    THEN 1
        WHEN s.CHAN_C='Corporate' THEN 6
        WHEN s.CHAN_C='GDS'       THEN 5
        ELSE 3 END
JOIN DIM_CUSTOMER cu ON cu.COUNTRY=s.COUNTRY_C
                    AND cu.SEGMENT=s.SEGMENT_C
                    AND cu.REPEATGUESTFLAG=s.RPT_C;
COMMIT;

SELECT COUNT(*) AS FACT_ROWS FROM FACT_BOOKINGS;   -- expect 119,390
